fix: fully implement rule 219
baloise-incubator/spectral-ruleset pull request #24
Opened 2022-02-20 20:09 UTC by dweber019

2022-02-22 16:55 UTC, leubedane requested changes

2022-02-24 14:10 UTC, dweber019 commented on zalando.yml
> +          match: ^(component-internal|business-unit-internal|company-internal|external-partner|external-public)$
agree will change it

2022-02-28 06:57 UTC, leubedane commented on zalando.yml
> +          match: ^(component-internal|business-unit-internal|company-internal|external-partner|external-public)$
We will also need to add an entry to our documentation, i guess

2022-03-29 14:56 UTC, leubedane commented on zalando.yml
> +          match: ^(component-internal|business-unit-internal|company-internal|external-partner|external-public)$
Done

2022-04-03 11:54 UTC, leubedane commented on baloise.yml
> +          match: ^(component-internal|business-unit-internal|company-internal|external-partner|external-public)$
You are right, the change is missing, I will fix it :-)

2022-04-03 12:03 UTC, leubedane commented on baloise.yml
> +          match: ^(component-internal|business-unit-internal|company-internal|external-partner|external-public)$
Now it should be right. @dweber019  and @joachimprinzbach

2022-04-05 07:03 UTC, leubedane approved these changes

2022-04-05 07:04 UTC, merged